### PR TITLE
Make the library isomorphic

### PR DESCRIPTION
**Pull request by erizocosmico**

### CODE REVIEW

**Comment by seangenabe** [comment]
I don't see how this code does anything, considering pinkie-promise works fine with almost exactly [the same code](https://github.com/floatdrop/pinkie-promise/blob/master/index.js).

**Comment by erizocosmico** [comment]
If Promise is already defined at top level scope don't require it. `global` is not defined in the browser, for example, and the library does not work now in the browser. With these changes it does.

**Comment by seangenabe** [comment]
I wasn't aware `global` isn't a JS standard. **EDIT**: `global` _is_ an EcmaScript 5 standard, conversely, browsers are the ones not supporting it.

Anyway, asking me to do this is like asking me to wrap the module in a UMD wrapper. I don't intend to support browsers, directly anyway. I only want to support node.js for now and keep my code as simple as possible. I'd suggest using [browserify, et al](https://github.com/substack/insert-module-globals) or any other module transformer for this case.

Since `module` isn't really a JS standard, won't `module` give an error too, on browser environments? I'm curious where you're testing this.

Also, this code still won't work for old browsers as there's still a reference to `global` there.

**Comment by erizocosmico** [comment]
Browserify uses module.exports. But does not convert global to window. There is no reference to global, look at the last commit.

**Comment by seangenabe** [comment]
Browserify defines `global`, it's even [documented](https://www.npmjs.com/package/browserify).

browserify global

Here's an excerpt of code transformed with browserify with just `global` as the content:

```
(function (global){
global

}).call(this,typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})
```

(using browserify@8.1.1)

**Pull request closed without merging**
